# Generated by Django 3.0.5 on 2020-04-19 21:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import utils.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ToDo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('status', models.PositiveSmallIntegerField(choices=[(0, 'NEW'), (1, 'IN_PROGRESS'), (2, 'CURRENT'), (3, 'DONE')], default=0)),
            ],
            options={
                'verbose_name': 'todo',
                'verbose_name_plural': 'todos',
            },
        ),
        migrations.CreateModel(
            name='WorkToDo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('todo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.ToDo')),
            ],
            options={
                'verbose_name': 'Work to do',
                'verbose_name_plural': 'List of work to do',
            },
        ),
        migrations.CreateModel(
            name='ToDoList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(default='')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='media/images', validators=[utils.validators.extension_validator, utils.validators.file_size_validator])),
                ('favorite', models.BooleanField(default=False)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'To do List',
                'verbose_name_plural': 'To do Lists',
            },
        ),
        migrations.AddField(
            model_name='todo',
            name='list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='core.ToDoList'),
        ),
        migrations.CreateModel(
            name='StudyToDo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('todo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.ToDo')),
            ],
            options={
                'verbose_name': 'Work to learn',
                'verbose_name_plural': 'List of work to learn',
            },
        ),
    ]
