TODO_NEW = 0
TODO_IN_PROGRESS = 1
TODO_DONE = 3
TODO_CURRENT = 2

TODO_STATUSES = (
    (TODO_NEW, 'NEW'),
    (TODO_IN_PROGRESS, 'IN_PROGRESS'),
    (TODO_CURRENT, 'CURRENT'),
    (TODO_DONE, 'DONE')
)